on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
      # Checkout the repository code.
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Logn to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Project
        uses: docker/build-push-action@v4
        with:
          context: .
          
          #Slim it!
      - name: Slim Project
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ghcr.io/${{ github.repository }}/mkdocs
          tag: "slim"
          
          push: true
          tags: |
            ghcr.io/${{ vars.REPOSITORY }}:latest
            ghcr.io/${{ vars.REPOSITORY }}:${{ github.run_number }}
