on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    steps:
      # Checkout the repository code.
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Logn to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Project
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mkdocs:latest
            ghcr.io/${{ github.repository }}/mkdocs:${{ github.run_number }}

      - name: Slim Project
        run: |
          docker pull ghcr.io/${{ github.repository }}/mkdocs:latest
          docker tag ghcr.io/${{ github.repository }}/mkdocs:latest mkdocs:latest
          docker-slim mkdocs:latest --http-probe=false
          docker tag mkdocs:slim ghcr.io/${{ github.repository }}/mkdocs:slim
          docker push ghcr.io/${{ github.repository }}/mkdocs:slim

      - name: Push Slimmed Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mkdocs:slim
            ghcr.io/${{ github.repository }}/mkdocs:slim-${{ github.run_number }}
